### PR TITLE
Add Center Credentials

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the `com.simperium.android:simperium` library dependency from `0.9.0` to `0.9.1` in order to center the view on large screens as described in https://github.com/Simperium/simperium-android/pull/211.  See the screenshots below for illustration.

Before|After
-|-
|
|

### Test
These changes only apply to devices 640dp x 480dp and larger.  Use a device that falls into the `layout-large` category (e.g. Nexus 9 tablet in landscape orientation) for testing.

0. Clear app data.
1. Tap ***Sign Up*** button.
2. Notice layout is centered.
3. Tap back arrow in app bar.
4. Tap ***Log In*** button.
5. Tap ***Log In with Email*** button.
6. Notice layout is centered.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by anitaa1990** [comment]
Will wait for design review to pass before merging 👍

**Comment by SylvesterWilmott** [comment]
Looks good @theck13 

I'm curious where the max width is coming from

**Comment by theck13** [comment]
@SylvesterWilmott, this is effectively the same change as https://github.com/Simperium/simperium-android/pull/211.  This pull request just updates the Simperium library to use the changes from that pull request.  The maximum width is coming from the Simperium library `width_layout` value, which is also used for the width of all bottom sheet dialogs.

**Comment by theck13** [comment]
Thanks @anitaa1990 and @SylvesterWilmott!  This pull request looks good to merge whenever you're ready, @anitaa1990.

**Pull request merged**
