### PR TITLE
Add Styled Widgets (Part 2)

### PR DESCRIPTION
**Pull request by theck13**
### Fix
This is the second part in a series of pull requests to add styled widgets to the app.  The pull requests are split into parts in an attempt to make the changes smaller.  This part adds the selected app style to the note list widget.  See the screenshots below for illustration.

add_styled_widgets_2

### Test
The first steps add the **_Note List (Light)_** and **_Note List (Dark)_** widgets to the home screen.  These steps assume the AOSP launcher (i.e. Nexus/Pixel launcher).  The steps to add the widget to the home screen may be slightly different based on the launcher used.  Other steps should be the same regardless of launcher.
1. Long-press home screen.
2. Tap ***Widgets*** option.
3. Scroll to ***Simplenote*** widget.
4. Long-press ***Note List (Light)*** widget.
5. Place ***Note List (Light)*** widget on home screen.
6. Notice note list shown in widget with light theme.
7. Long-press home screen.
8. Tap ***Widgets*** option.
9. Scroll to ***Simplenote*** widget.
10. Long-press ***Note List (Dark)*** widget.
11. Place ***Note List (Dark)*** widget on home screen.
12. Notice note list shown in widget with dark theme.

After adding the note list widgets to the home screen, follow the steps below for each style by choosing a different style in Step 5 each time.
1. Open navigation drawer.
2. Tap ***Settings*** item in drawer.
3. Tap ***Style*** item under ***Appearance*** section.
4. Notice ***Style*** screen with ***Default***, ***Matrix***, ***Publication***, ***Mono***, ***Sepia***, ***Black***, and ***Classic*** styles.
5. Tap ***Default***, ***Matrix***, ***Publication***, ***Mono***, ***Sepia***, ***Black***, or ***Classic*** style.
6. Notice selected style is shown in ***Styles***.
7. Tap back arrow in navigation bar.
8. Notice selected style is shown in ***Settings***.
9. Tap back arrow in navigation bar.
10. Notice selected style is shown in ***All Notes***.
11. Tap back arrow in navigation bar.
12. Notice selected style is shown in note list widgets.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

#### Note
Contact me for an installable build.

### Release
These changes do not require release notes.  `RELEASE-NOTES.txt` will be updated once the styles feature is complete.

### CODE REVIEW

**Comment by ThomazFB** [comment]
Hey @theck13, just to let you know that I've started the review and I'm planning to finish it today by EOD, took me a while to configure everything but now I'm able to test everything!

**Comment by ThomazFB** [comment]
Hey @theck13 , great work! The widgets creation, actions, and styles are working just fine! I've noticed some behaviors that I'm wondering if they're expected:

- The `Note List (Dark)` only opens the app with the Theme set at the `Settings` options, should it forcefully open with the Dark Theme?
- Sometimes at the Widget list of my device the preview images don't show up, instead, the app icon appears for each widget option, is this a known issue? Maybe it's an issue with my device factory build (Motorola One Fusion+).

Thank you for your time!

**Comment by theck13** [comment]
> The `Note List (Dark)` only opens the app with the Theme set at the `Settings` options, should it forcefully open with the Dark Theme?

The widget chosen should only update the font and accent color based on the style selected in the app.  The overall theme of the widget does not change based on the theme selected in the app (i.e. **_Light_**, **_Dark_**, **_Dark at night only_**, and **_System default_**) or operating system (i.e. **_Dark theme_** enabled/disabled).  That's why there are **_Light_** and **_Dark_** versions of both the **_Note_** and **_Note List_** widgets so the user can specify which type of widget they want exactly.

> Sometimes at the Widget list of my device the preview images don't show up, instead, the app icon appears for each widget option, is this a known issue? Maybe it's an issue with my device factory build (Motorola One Fusion+).

Every launcher shows the widget selection a little differently.  See the screenshots below for illustration.

launcher

Which launcher is installed by default on the Motorola One Fusion+?

**Review by iamthomasbishop — APPROVED** [review]
@theck13 As discussed in dm, my only feedback was that I think these would benefit from a bit more whitespace/padding, but it sounds like the scope of this ticket is the color themes/styles, which all look good afaict. @SylvesterWilmott obviously has more insight into the specific theme details (so he has the final say) but I'm going to go ahead and approve on my end.

**Comment by ThomazFB** [comment]
Hey @theck13! Thanks for your reply and clarification! Considering what you've said about the widget themes, I can say that for me everything is working just fine!

> Which launcher is installed by default on the Motorola One Fusion+?

It's the Pixel one! But the main problem happening was more about the icon of each Widget, these `To-Do List` images representing each Widget type weren't showing up under the horizontal list as expected, it was only the Simplenote app appearing for each Widget option. Sadly, I couldn't reproduce that anymore and can't take a screenshot to show you with more detail what was happening, after I reinstalled the app the issue never showed up, so I'm supposing this was more of a problem around the OS instead of the app.

Anyway, everything seems to be work just fine from here, LGTM! :shipit:

**Review by ThomazFB — APPROVED** [review]

**Pull request merged**
