### PR TITLE
Update Icon Drawables

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the icon toolbar color tint and drawables.  See the screenshots below for illustration.

update_icon_drawables_light

update_icon_drawables_dark

### Test
1. Open navigation drawer.
2. Notice updated icons appear as shown above.
3. Close navigation drawer.
4. Notice updated menu and search icons appear as shown above.
5. Tap any note in list that has been published.
6. Notice action icons appear as shown above.
7. Tap ***Share*** action in app bar.
8. Notice icons appear as shown above.
9. Tap back arrow in app bar.
10. Open navigation drawer.
11. Tap ***Edit*** button in ***Tags*** group.
12. Notice icons appear as shown above.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks fantastic!

For the notes list, we can use the `published` icon from the 16px set. For the pinned icon let's continue with the dot until I can create a 16px version of the pinned icon.

**Comment by theck13** [comment]
I updated the published icon in 3eb5d0c9.  See the screenshots below for illustration.

update_icon_drawables_light

update_icon_drawables_dark

**Comment by SylvesterWilmott** [comment]
Thanks for the changes

I noticed you changed the colours of the icons in the app bar, can we apply the same changes to the navigation drawer as well?

Everything else looks great

**Comment by theck13** [comment]
I updated the navigation drawer icons to match the toolbar icons in 071007c5.  See the screenshots below for illustration.

update_icon_drawables_drawer

**Comment by SylvesterWilmott** [comment]
Looks good, thanks @theck13

**Comment by theck13** [comment]
@AmandaRiu, there were a couple changes since you first reviewed this pull request.  It has passed design review and good to merge whenever you're ready!

**Pull request merged**
