### PR TITLE
[Auth] Added Accept-Language header for localizing magic link email.

### PR DESCRIPTION
**Pull request by notandyvee**
### Fix

Adds `Accept-Language` header when requesting magic link.

### Test

- [ ] You need to have your device spoof a specific locale. `es_ES` or `de_DE`.
- [ ] The magic link email should be in a language other than english.

### Release
n/a

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>HeadersInterceptor</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by roundhill — APPROVED** [review]
Tested well! Do you think it's necessary to add it to every request? I suppose it won't hurt anything and may actually fix other problems with locale :)

**Comment by notandyvee** [comment]
> Do you think it's necessary to add it to every request?

Necessary. No. I could move it back to the single place if we care. It's not a lot of extra characters, and lays the foundation to add more necessary headers.

**Pull request merged**
