### PR TITLE
Add a bottom padding to notes list so that all note rows can be fully visualized

### PR DESCRIPTION
**Pull request by iskandergaba**
The FAB now hides whenever the user scrolls down, giving a better visibility for the note items at the bottom of the screen. (Issue #311)

screenshot

### CODE REVIEW

**Comment by roundhill** [comment]
Pretty cool! Do you know of other apps that auto hide the FAB? I'd like to compare the behaviors.

**Comment by iskandergaba** [comment]
> Pretty cool! Do you know of other apps that auto hide the FAB? I'd like to compare the behaviors.
 
I cannot really think of any at the moment, but the behavior presented is the standard one in all guides available online.

See:
- https://www.dev2qa.com/android-hide-floating-action-button-while-recyclerview-scroll-example
- https://androidessence.com/android/hide-the-floatingactionbutton-when-scrolling-recyclerview
- https://guides.codepath.com/android/floating-action-buttons
- https://uxplanet.org/floating-action-button-in-ux-design-7dd06e49144e
- http://codeworks.it/blog/?p=460

**Comment by roundhill** [comment]
@iskandergaba after reviewing other apps it seems like this is no longer used much (checked Gmail, Drive, and Messaging).

One thing we could do though is add padding to the bottom of the list view so that the FAB won't cover up the last note in the list. You can see how Google Drive does this. Are you interested in adding that?

**Comment by iskandergaba** [comment]
@roundhill I will look into it

**Comment by iskandergaba** [comment]
@roundhill I have implemented the requested changes and reverted back the hiding behaviour. I have changed the title of this pull request to reflect that. As the commit messages clarifies, the size of the bottom padding is carefully calculated to accommodate the FAB and its paddings in a clean symmetrical fashion. Below are a couple of screenshots of the change.

**Light**

Screenshot 1

**Dark**

Screenshot 2

**Comment by roundhill** [comment]
Awesome! Thanks @iskandergaba! :shipit:

**Pull request merged**
