### PR TITLE
Update Note Editor

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update managing tags in the note editor with interactive chips.  See the screenshots and animation below for illustration.

update_note_editor_tags

<a href="https://user-images.githubusercontent.com/3827611/64477898-f8edab80-d15d-11e9-8c2e-9d55939eaebd.gif"></a>

### Test
1. Tap any note in list with tags.
2. Notice tag interface at bottom of ***Edit*** tab.
3. Notice close button is hidden in tag chips.
4. Tap tag chip.
5. Notice close button is shown in tag chip from Step 4.
6. Tap close button in tag chip from Step 4.
7. Notice tag chip is removed.
8. Tap ***Add tag...*** field.
9. Enter first letter of tag chip from Step 4.
10. Notice popup menu shows tag(s) matching entered letter.
11. Tap tag in popup menu.
12. Notice tap from Step 11 added as tag chip.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
This looks fantastic! Thanks

Can we try increasing the space between the last line of text in the note and the tags? Also, how is that autocomplete being positioned? Can we force it to be "full width" as we have it currently?

**Comment by theck13** [comment]
> Can we try increasing the space between the last line of text in the note and the tags?

I increased the space between to top and bottom of the note content to 24dp.

> Also, how is that autocomplete being positioned? Can we force it to be "full width" as we have it currently?

It was set to 320dp originally.  I updated that width to match the note content view.

Also, I updated the side padding from 16dp to 20dp, the tag chips were made to behave like radio buttons rather than checkboxes (i.e. single-selection rather than multiple-selection), and the shadow shown when tapping tag chips was removed.  See the screenshots and animation below for illustration.

update_note_editor_tags

<a href="https://user-images.githubusercontent.com/3827611/64911272-7af54b80-d6ed-11e9-8a13-4bc849262afd.gif"></a>

**Comment by SylvesterWilmott** [comment]
Looks great @theck13 !

Thanks

**Comment by theck13** [comment]
As we discussed, I added creating a new tag when text is entered and next button is tapped on the keyboard.  Also, I updated the tag input view to expand when entering long text.  See the animation below for illustration.

Before|After
-|-
tags_input_before|tags_input_after

**Comment by SylvesterWilmott** [comment]
>I added creating a new tag when text is entered and next button is tapped on the keyboard. Also, I updated the tag input view to expand when entering long text. See the animation below for illustration.

Thanks @theck13 !

**Comment by theck13** [comment]
I updated text size in the tag input view pop-up menu to 16sp as we discussed.  See the screenshots below for illustration.

update_note_editor_tags_popup

**Comment by SylvesterWilmott** [comment]
Thanks for the changes @theck13

**Pull request merged**
