### PR TITLE
Add Membership Setting

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Add a **_Membership_** setting under the **_Account_** section to the **_Settings_** screen.  The setting will show if the Simplenote account logged into the device is **_Free_** or **_Premium_**.  In both cases, tapping the Membership setting will open https://app.simplenote.com in the device's default browser app.  If no browser app is installed on the device, the "Unable to open website. No browser available." message will be shown.  If the Simplenote account is **_Free_**, an **_Upgrade_** button will shown in the setting, which will direct to https://app.simplenote.com as well.  See the screenshots below for illustration.

add_membership_setting

If an account is **_Free_**, all **_Premium_** features will be disabled.  As of now, the only **_Premium_** feature is styles.  If an account is changed from **_Premium_** to **_Free_**, the **_Default_** style will be selected automatically regardless of the previously selected style and the other styles will be locked.

### Test
Since the backend for **_Free_**/**_Premium_** accounts is not implemented yet, all accounts are considered **_Premium_** in order to fully develop and test **_Premium_** features.  In order to toggle the **_Free_**/**_Premium_** setting, update the [`PrefUtils.isPremium(Context)` method](https://github.com/Automattic/simplenote-android/blob/feature/add-app-styles/Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java#L165) to return `false`/`true` for **_Free_**/**_Premium_**, respectively.

#### Free
1. Open navigation drawer.
2. Tap **_Settings_** item in drawer.
3. Notice **_Membership_** setting under **_Account_** section.
4. Notice **_Free_** in **_Membership_** setting.
5. Notice **_Upgrade_** button for **_Free_** in **_Membership_** setting.
6. Tap **_Style_** setting under **_Appearance_** section.
7. Notice **_Default_** style is selected.
8. Notice other styles are locked.
9. Tap any style other than **_Default_**.
10. Notice **_Style Locked_** dialog is shown.
11. Tap **_No_** button in dialog.
12. Notice dialog is dismissed.
13. Tap any style other than **_Default_**.
14. Notice **_Style Locked_** dialog is shown.
15. Tap **_Yes_** button in dialog.
16. Notice https://app.simplenote.com is shown in browser (if installed).

#### Premium
1. Open navigation drawer.
2. Tap **_Settings_** item in drawer.
3. Notice **_Membership_** setting under **_Account_** section.
4. Notice **_Premium_** in **_Membership_** setting.
5. Notice no **_Upgrade_** button for **_Premium_** in **_Membership_** setting.
6. Tap **_Style_** setting under **_Appearance_** section.
7. Notice **_Default_** style is selected.
8. Notice other styles are not locked.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

#### Note
Contact me for an installable build.

### Release
These changes do not require release notes.  `RELEASE-NOTES.txt` will be updated once the styles feature is complete.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks good!

The "Style Locked" dialog seems a little bit wordy. Based on the copy from the design on web we can use:

**Premium Style**
To use this style you must have a premium membership.
[Cancel][Learn More]

I would also like to create our own lock icon, but I'll ping you when that is done.

**Comment by theck13** [comment]
Would the **_Learn More_** button take them to an informative page about Simplenote memberships or to the page to upgrade?  What about just making that button **_Upgrade_** like this?

<a href="https://user-images.githubusercontent.com/3827611/99677722-468ac700-2a37-11eb-830c-168f1a1eaed2.png"></a>

**Comment by SylvesterWilmott** [comment]
This would be a good spot for experimentation. According to the most recent web designs, "Learn More" will direct you to a page with a list of all premium features. The payment page will contain a smaller, less exhaustive list of features.

I'm happy to go with "Upgrade" for the moment.

**Comment by theck13** [comment]
I updated the dialog title and message in c6a3ce72.  See the screenshot below for illustration.

<a href="https://user-images.githubusercontent.com/3827611/99677722-468ac700-2a37-11eb-830c-168f1a1eaed2.png"></a>

**Review by AmandaRiu — APPROVED** [review]
Tried both free and premium. Everything looks great and works as expected!! :shipit:

**Comment by AmandaRiu** [comment]
Will merge once this PR passes design review.

**Review by SylvesterWilmott — APPROVED** [review]
Looks great, Thanks!

**Pull request merged**
