### PR TITLE
Add codefreeze lane

### PR DESCRIPTION
**Pull request by loremattei**
This PR adds a lane to automate some of the steps of the code freeze process. 
This PR builds on top of https://github.com/Automattic/simplenote-android/pull/744 and should be tested and merged after 744 is merged. 

# To Test
1. Run `bundle install`.
2. Run `bundle exec fastlane code_freeze`.
3. When prompted, verify that the versions are right and confirm. 
4. Verify that the script completes without errors.
5. Verify that a new branch has been created (currently it should be `release/1.9`) and pushed. 
6. Verify that the version has been updated (`1.9-rc-1`).
7. Verify that a new `1.9-rc-1` tag has been added and pushed. 
8. Verify that the snowflake tag has been added to the relevant milestone (currently `1.9`).
9. Verify that `simplenoteandroid_prs_list_1.8.1_1.9.txt` has been created in your home folder with the changelog. 

### Clean up
1. Remove the snowflake tag from the `1.9` milestone.
2. Remove the branch protection from `release/1.9`.
3. Delete the `release/1.9` branch from your local repository and from GitHub.
4. Delete the `1.9-rc-1` tag from your local repository and from GitHub.

### CODE REVIEW

**Comment by jtreanor** [comment]
# To Test
- [ ] Run `bundle install`.
- [ ] Run `bundle exec fastlane code_freeze`.
- [ ] When prompted, verify that the versions are right and confirm. 
- [ ] Verify that the script completes without errors.
- [ ] Verify that a new branch has been created (currently it should be `release/1.9`) and pushed. 
- [ ] Verify that the version has been updated (`1.9-rc-1`).
- [ ] Verify that a new `1.9-rc-1` tag has been added and pushed. 
- [ ] Verify that the snowflake tag has been added to the relevant milestone (currently `1.9`).
- [ ] Verify that `simplenoteandroid_prs_list_1.8.1_1.9.txt` has been created in your home folder with the changelog. 

### Clean up
- [ ] Remove the snowflake tag from the `1.9` milestone.
- [ ] Remove the branch protection from `release/1.9`.
- [ ] Delete the `release/1.9` branch from your local repository and from GitHub.
- [ ] Delete the `1.9-rc-1` tag from your local repository and from GitHub.

**Comment by jtreanor** [comment]
😱

**Comment by loremattei** [comment]
Got the same here: https://github.com/Automattic/simplenote-android/pull/746#issuecomment-514141430.

**Comment by jtreanor** [comment]
@loremattei Yep, its fixed now: https://github.com/Automattic/peril-settings/pull/13

**Comment by loremattei** [comment]
Yep! Was just looking at it :-)

**Pull request merged**
