### PR TITLE
Update Lock Icon

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the lock icon to the new Simplecon, https://github.com/Automattic/Simplecons/pull/8.  The lock icon is shown on the **_Style_** screen when an account is **_Free_**.  See the screenshots below for illustration.

update_lock_icon

### Test
Since the backend for **_Free_**/**_Premium_** accounts is not implemented yet, all accounts are considered **_Premium_** in order to fully develop and test **_Premium_** features.  In order to see the locked styles with the lock icon, update the [`PrefUtils.isPremium(Context)` method](https://github.com/Automattic/simplenote-android/blob/a49d9a6c78d770c188834299d7cda3e719a35b13/Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java#L165) to return `false`, which will set the account as **_Free_**.
1. Open navigation drawer.
2. Tap **_Settings_** item in drawer.
3. Tap **_Style_** setting under **_Appearance_** section.
4. Notice **_Default_** style is unlocked and selected.
5. Notice other styles are locked with new lock icon.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

#### Note
Contact me for an installable build.

### Release
These changes do not require release notes.  `RELEASE-NOTES.txt` will be updated once the styles feature is complete.

### CODE REVIEW

**Review by SylvesterWilmott — APPROVED** [review]
Looks good! Thanks

**Comment by nbradbury** [comment]
@theck13 I see the previous icon was white, too, but I'm wondering if we need a separate lock icon for dark mde?

Screenshot_20201125_115846

**Comment by theck13** [comment]
My first thought is that a darker color icon in **_Dark_** theme may make the lock less visible with the black circular translucent circular background.  Are you saying we should make the circular translucent background for the lock white and the lock icon dark for _**Dark**_ theme?  What do you think, @SylvesterWilmott?  Maybe something like this?

update_lock_icon_tint

**Comment by SylvesterWilmott** [comment]
Ah yes! The lighter icon background looks much nicer in dark mode. Thanks for the suggestion @nbradbury

**Comment by SylvesterWilmott** [comment]
Now that I look again, I think we can bring up the opacity of those backgrounds a little. I think it worked fine with the filled icon, but with the line style, it clashes a little with the text beneath it.

**Comment by theck13** [comment]
What opacity should we use?  The circular background in the screenshots above is using 60% opacity.

update_lock_icon_tint

**Comment by SylvesterWilmott** [comment]
80% looks good!

**Comment by theck13** [comment]
I added icon tint and background colors for **_Light_** and **_Dark_** themes in c8ac59f and 33d0eb4.  I updated the translucent circular background color from 60% to 80% opacity in e6b3c8a.  See the screenshots below for illustration.

update_lock_icon_update

**Review by nbradbury — APPROVED** [review]
Looks great! :shipit:

**Pull request merged**
