### PR TITLE
Fix editor's background color in landscape mode with dark theme

### LINKED ISSUE #1410: App Switches to Light Mode When Editing in Landscape Orientation
### Expected
When dark mode is enabled, rotating to landscape orientation while editing should retain dark mode.

### Observed
Instead, the editor switches to light mode.

### Reproduced
1. Enable dark mode in Simplenote's app settings.
2. Open a note and start editing.
3. Rotate to landscape orientation.

https://user-images.githubusercontent.com/42454301/124658653-05cea980-de72-11eb-8f8b-0a9fec888ba7.mp4

Device Make: Google
Device Model: Pixel 3
Android Version: 11
Simplenote Version: 2.18

### PR DESCRIPTION
**Pull request by danilo04**
Fixes #1410.

### Fix

When dark mode is enabled, rotating to landscape orientation while editing should retain dark mode. We did this by disabling full-screen keyboard (`android:imeOptions="flagNoExtractUi"`) and hiding toolbar for landscape mode in phones. 

**Before:**

https://user-images.githubusercontent.com/42454301/124658653-05cea980-de72-11eb-8f8b-0a9fec888ba7.mp4

**After:**

https://user-images.githubusercontent.com/195721/130622851-e273e4b6-6673-4e57-ab55-e2bd2e293b99.mp4

### Test

1. Go to settings and enable dark mode
2. Tap on a new note or a note from the notes list
3. Start typing on the note
4. Rotate the phone to landscape mode
5. The tabs and toolbar should hide and the background of the text editor should remain dark
6. Rotate the phone again
7. The tabs and toolbar should be shown again
8. Rotate the phone to landscape mode
9. The tabs and toolbar should hide and the background of the text editor should remain dark
10. Hide the keyboard
11. The tabs and toolbar should be shown again
12. Disable markdown
13. Rotate the phone to landscape mode
14. Start typing on the note
15. The toolbar should hide and the background of the text editor should remain dark
16. Hide the keyboard
17. The toolbar (not the tabs) should be shown again

### Review

Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release

`RELEASE-NOTES.txt` was updated in 31fedccb72994eaf4110ea59f43ab3b6b6503a36 with:
> Fixed editor's background color in landscape mode with dark theme

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Thanks for doing this @danilo04 

I think this is a good improvement, not only because the background is displayed correctly in dark mode but also for the general experience while editing in landscape on the phone.

The transition when showing/hiding the keyboard is a bit janky in landscape mode, is this something that can be tweaked or is everything being handled by the system there?

**Comment by danilo04** [comment]
Howdy @SylvesterWilmott 👋 .

> The transition when showing/hiding the keyboard is a bit janky in landscape mode

I think we can smooth the transitions since it is our code that hides and shows the toolbar, but let me check first to see what is the best option to do this.

**Comment by SylvesterWilmott** [comment]
Thanks for the update @danilo04 and thanks for spending the time trying to smooth out the transition.

I think there isn't much of a drastic improvement in delaying the app bar transition since the jankiness observed before is still present. I would suggest reverting the latest and commit and **embrace the jank**. The improvement in the experience of editing in landscape outweighs the jerkiness of the transition.

**Comment by danilo04** [comment]
@SylvesterWilmott reverted in faa25ba184f4ddf4aa36811a02536edde8dd1b80. I have created #1465 to tackle this issue later since it's a non-blocker.

**Review by SylvesterWilmott — APPROVED** [review]

**Review by AmandaRiu — APPROVED** [review]
Tested and works! :shipit:

**Pull request merged**
