### PR TITLE
Issue/841 update search list

### LINKED ISSUE #841: Search: Update Search List View
Update the list view containing search results as shown in the mockups below.

<a href="https://user-images.githubusercontent.com/3827611/66611704-9af91d00-eb7c-11e9-94ec-66ecfa17850e.png"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://user-images.githubusercontent.com/3827611/66611708-9cc2e080-eb7c-11e9-8220-16f4a18ad694.png"></a>

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the list view containing search results to close #841.  These changes include:
- Hide ***Pinned*** icon when searching
- Hide ***Published*** icon when searching
- Show date text when searching if ***Sort order*** setting one of:
  - Newest modified date
  - Oldest modified date
  - Newest created date
  - Oldest created date

Updating the sort order within the search list will be included in a subsequent pull request.  See the screenshots and animation below for illustration.

841_update_search_list

Created/Modified|Alphabetical
-|-
841_update_search_list_date_show|841_update_search_list_date_hide

### Test
The two search scenarios to test are when the date text is shown based on the ***Sort order*** setting.  ***Newest created date***, ***Oldest created date***, ***Newest modified date***, and ***Oldest modified date*** show the date text.  ***Alphabetically, A-Z*** and ***Alphabetically, Z-A*** do not.
#### Created / Modified
1. Set ***Sort order*** setting to ***Newest created date***, ***Oldest created date***, ***Newest modified date***, or ***Oldest modified date***.
2. Tap ***Search*** action in top app bar.
3. Notice ***Pinned*** icons hidden.
4. Notice ***Published*** icons hidden.
5. Notice date text shown.

#### Alphabetical
1. Set ***Sort order*** setting to ***Alphabetically, A-Z*** or ***Alphabetically, Z-A***.
2. Tap ***Search*** action in top app bar.
3. Notice ***Pinned*** icons hidden.
4. Notice ***Published*** icons hidden.
5. Notice date text hidden.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Thanks @theck13 this looks great.

One little nitpick can we just align the timestamp so it's centred against the title. It's only off by about 1 or 2dp.

Screenshot 2019-10-28 at 10 24 04

**Comment by SylvesterWilmott** [comment]
When performing a search we show the note title in the body section. Is there any particular reason what we do this or are we able to remove the note title from the body while searching?

Screenshot 2019-10-28 at 10 28 56

**Comment by theck13** [comment]
> One little nitpick can we just align the timestamp so it's centred against the title. It's only off by about 1 or 2dp.

I updated the date view to be centered vertically in bfd8c294.  See the screenshots below for illustration.

841_update_search_list_date

> When performing a search we show the note title in the body section. Is there any particular reason what we do this or are we able to remove the note title from the body while searching?

That's necessary for the full-text search to highlight the correct text when viewing the note after tapping it in the search results.  That behavior wasn't changed in this pull request.

**Comment by theck13** [comment]
@AmandaRiu, these changes are good to merge whenever you're ready!

**Pull request merged**
