### PR TITLE
Update Selected Color

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the selected background color of the ***Light*** theme from `blue_0` (`#eff3f7`) to `blue_5` (`#c6def6`) for higher contrast and better accessibility.  See the screenshots below for illustration.

update_selected_color

### Test
0. Set ***Theme*** to ***Light***.
1. Open navigation drawer.
2. Notice selected background color is `blue_5` (`#c6def6`).
3. Close navigation drawer.
4. Long-press any note in list.
5. Notice selected background color is `blue_5` (`#c6def6`).
6. Notice app bar background color is `blue_5` (`#c6def6`).

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Sorry for the delay on this one, I think it got a little lost.

The colour change looks good. In regards to the navigation bar, are we able to keep this white in selection state? Probably something to be addressed in another PR so I am removing the design label.

**Comment by theck13** [comment]
> In regards to the navigation bar, are we able to keep this white in selection state?

If by navigation bar, you are referring to the app bar with the ***3 notes selected*** text shown in the screenshots above, then yes.  We can make that background whatever color we want.  However, it's usually set to be the same color as the selected item background since it helps signify a different mode is activated (i.e. multi-select mode).

**Comment by SylvesterWilmott** [comment]
>However, it's usually set to be the same color as the selected item background since it helps signify a different mode is activated

It seems that in Google's apps that now use the white app bar, they keep the app bar white when in selected state.

**Comment by theck13** [comment]
> It seems that in Google's apps that now use the white app bar, they keep the app bar white when in selected state.

Google apps don't really have a standard app bar.  They have a search view that changes to a more standard app bar when multi-select mode is active.

We can set that to whatever we want though.  Let me know if this pull request is good as is or if we want to leave the top app bar background color unchanged for ***Light*** and ***Dark*** themes in multi-select mode.

**Comment by SylvesterWilmott** [comment]
Let's remove the background colour when in selected state:

- Remove background colour from app bar when in selected state
- Use Blue for app bar items when in selected state (including text)

**Comment by theck13** [comment]
> - Remove background colour from app bar when in selected state

I updated the background color in cdf877e5.

> - Use Blue for app bar items when in selected state (including text)

I updated the text and icon color in 46da357c.

See the screenshots below for illustration.

update_selected_color_again

**Comment by SylvesterWilmott** [comment]
Looks really good! Thanks for the changes

**Comment by theck13** [comment]
@AmandaRiu, these change look good to merge whenever you're ready!

**Pull request merged**
