### PR TITLE
Update Empty Views

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the empty views throughout the app by adding images and changing the copy.  See the screenshots below for illustration.

update_empty_views_light

update_empty_views_dark

#### Note
These changes do not include the updated gray colors used for ***Dark***.  Those are addressed in a separate pull request.

### Test
1. Move all notes to ***Trash***.
2. Tap ***All Notes*** in navigation drawer.
3. Notice ***Create your first note*** empty view.
4. Tap ***Untagged Notes*** in navigation drawer.
5. Notice ***Create an untagged note*** empty view.
6. Tap any tag under ***Tags*** section in navigation drawer.
7. Notice ***No notes tagged "TAG"*** empty view where TAG is tag selected in Step 4.
8. Restore all notes from ***Trash***.
9. Tap ***Trash*** in navigation drawer.
10. Notice ***Your trash is empty*** empty view.
11. Tap ***All Notes*** in navigation drawer.
12. Tap ***Search*** action in top app bar.
13. Enter any text not matching notes in search field.
14. Submit search with entered text.
15. Notice ***No notes found*** empty view.
16. Tap back arrow in top app bar.
17. Tap ***Edit*** button under ***Tags*** section in navigation drawer.
18. Tap delete button next to all tags.
19. Notice ***No tags*** empty view.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks great!

The intention was to have a separate one for empty search with only the string (and no icon), in landscape phone the message is obscured by the keyboard but I do like the portrait version. Can we make the empty search state an exception by hiding the icon in landscape mode?

**Comment by theck13** [comment]
> Unrelated to the PR though, is there an option to restore all the notes from Trash? I had to manually go to each note and click on the restore button there which was a bit cumbersome.

@anitaa1990, there isn't an other to restore all unfortunately.

> Can we make the empty search state an exception by hiding the icon in landscape mode?

I updated the search empty view in ed370e03.  The icon will be visible unless the device is not a large device in landscape orientation.

**Comment by SylvesterWilmott** [comment]
Looks good!

I noticed a small bug:

1. Perform a search that returns no results
2. Lock your phone
3. Unlock the phone and return to the app
4. The app now shows the incorrect empty state

**Comment by theck13** [comment]
Nice catch!  I updated the method that determines which empty state to show while searching in f0a8b09c.

**Comment by SylvesterWilmott** [comment]
Works perfectly, thanks!

**Pull request merged**
