### PR TITLE
Added keep screen on while editing in setting preference.

### PR DESCRIPTION
**Pull request by SuhanKoh**
It allows user to decide to keep the screen on while editing notes.
Also moved one of the hardcoded string for condense note to use the one defined in PrefUtils.
Added #500 

keepscreenon

### CODE REVIEW

**Comment by SuhanKoh** [comment]
Perhaps it could be on the tooltips on top of the editor, would that be too cluttered? May need some icons for this.

**Comment by roundhill** [comment]
Hmm it'd probably not work to do it in the editor unless you restarted the activity after enabling it, right? Maybe better to keep the setting like you've done.

`NotesActivity` can contain the editor when on a large device in landscape. So we'd probably need the same checks added to that activity to keep the screen on.

**Comment by SuhanKoh** [comment]
The checks is in ```NoteEditorFragment```, ```NotesActivity``` will load the fragment which would trigger the keep screen on flag, not sure if you meant move the check to ```NoteEditorActivity``` and ```NotesActivity```?

**Comment by roundhill** [comment]
> The checks is in NoteEditorFragment, NotesActivity will load the fragment which would trigger the keep screen on flag, not sure if you meant move the check to NoteEditorActivity and NotesActivity?

You're right, I didn't realize you could enable it from a fragment 👍

**Comment by roundhill** [comment]
@SuhanKoh I guess we let this die :) Did you want to still explore this? If you're able to enable from within the fragment then I think it'd be good to add a setting to the note info panel or something.

**Comment by SuhanKoh** [comment]
@roundhill Hi Dan, I don't think I have the capacity to do this at the moment, maybe someone else can pick it up, otherwise close it for now.

**Pull request closed without merging**
