### PR TITLE
Update Note Sort

### LINKED ISSUE #907: Search: Sort order changes affect note list sorting when app is closed during search
### Expected

I expect that the note list sort order will not be affected by the search sort order.

### Observed

If I go back to the note list, the note sort order is not affected by the search sort order.

However, if the app is closed while doing a search, any changes to the search sort order affect the note list sort order when the app is reopened.

### Reproduced

1. Open the app and confirm the note sort order (under Settings > Sort order).
2. Start a new search.
3. Enter any text to search your notes.
4. Notice that the search results use the same sort order as your notes list.
5. Change the sort order and/or direction for the search.
6. Tap the back arrow to go back to the notes list and notice that it has the original note sort order.
7. Start another new search.
8. Enter any text to search your notes.
9. Change the sort order and/or direction for the search.
10. Force close the app.
11. Reopen the app and notice that the notes list is using the selected sort order and direction from your last search (also saved under Settings > Sort order).

Make|Model|Android Version|App Version
-|-|-|-
Motorola|moto e5 play|8.1.0|2.3-rc-2

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the sort bar visibility and text to close #907.  The sort bar, which was only visible after submitting a search query, is updated to be always visible when searching and not.  The text is updated to match other platforms.  See the table below for details.

Before|After
-|-
Alphabetically, A-Z|Name: A-Z
Alphabetically, Z-A|Name: Z-A
Newest created date|Created: Newest
Oldest created date|Created: Oldest
Newest modified date|Modified: Newest
Oldest modified date|Modified: Oldest

The text updates also affect the **_Sort order_** item in **_Settings_**.  The order of the sort options is the sort bar match the designs.  The order of the sort options in the setting dialog are left in the order they were previously for a couple reasons.  The order is maintained for backwards compatibility with updated apps and the plan is to remove that setting completely at some point.  See the screenshots below for illustration.

update_note_sort

### Test
1. Notice sort bar is visible in note list.
2. Tap sort bar.
3. Notice popup menu with all sort options listed as described above.
4. Tap any sort option in popup menu.
5. Notice list sort order matches option selected.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
`RELEASE-NOTES.txt` was updated in ac09b7e1 with:
> Added sort bar at top of note list [https://github.com/Automattic/simplenote-android/pull/1284]

### CODE REVIEW

**Comment by AmandaRiu** [comment]
Hey @theck13 👋 Just to clarify on the sort itself...should it be case sensitive? I noticed during my testing that when changing to A-Z sorting it will sort by capital letters first and then by lowercase letters next...so if I have a note with a title "all good", it will show up after "Zoom call notes". Is that the expected functionality?

**Comment by theck13** [comment]
Yeah, the sorting is based on Unicode, which treats uppercase and lowercase differently.  That wasn't changed in this pull request, but it's something we might want to update at some point for platform parity.

**Review by AmandaRiu — APPROVED** [review]
Tested and verified! LGTM :shipit:

**Comment by pachlava** [comment]
[testing] fix/feature verified on Samsung A31 | Android 10 | Simplenote 2.17-rc-1

**Pull request merged**
