### PR TITLE
Update Keyboard Shortcuts

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update hotkey shortcuts for devices with hardware keyboards including an informational dialog.  **_Open Search_** was updated from `CTRL` `SHIFT` `S` to `CTRL` `SHIFT` `F`.  **_Next Match_** and **_Previous Match_** were added as `CTRL` `G` and `CTRL` `SHIFT` `G`.  The dialog and available shortcuts change based on the layout and screen being shown.  There are four variations of the dialog based on the available shortcut(s).

#### Large Device in Landscape
Shortcut|Keys
-|-
New Note|`CTRL` `SHIFT` `I`
Open Search|`CTRL` `SHIFT` `F`
Toggle Checklist|`CTRL` `SHIFT` `C`
Toggle Preview|`CTRL` `SHIFT` `P`
Toggle List|`CTRL` `SHIFT` `L`
Show Information|`CTRL` `I`
Show History|`CTRL` `H`
Show Share|`CTRL` `S`
Next Match|`CTRL` `G`
Previous Match|`CTRL` `SHIFT` `G`

##### Note List
Shortcut|Keys
-|-
New Note|`CTRL` `SHIFT` `I`
Open Search|`CTRL` `SHIFT` `F`

##### Editor with Edit Tab
Shortcut|Keys
-|-
Toggle Checklist|`CTRL` `SHIFT` `C`
Toggle Preview|`CTRL` `SHIFT` `P`
Show Information|`CTRL` `I`
Show History|`CTRL` `H`
Show Share|`CTRL` `S`
Next Match|`CTRL` `G`
Previous Match|`CTRL` `SHIFT` `G`

##### Editor with Preview Tab
Shortcut|Keys
-|-
Toggle Preview|`CTRL` `SHIFT` `P`

See the screenshots below for illustration.

update_kayboard_shortcuts_small

update_kayboard_shortcuts_large

### Test
Since the keyboard shortcuts dialog is only shown when the `CTRL` and `,` keys are pressed and the keyboard shortcuts only work on a device with a hardware keyboard, a device with a hardware keyboard is required to perform and verify the expected behavior.
#### Large Device in Landscape
1. Launch app without selecting note in list.
2. Press `CTRL` `,` keys.
3. Notice keyboard shortcuts dialog is shown.
4. Dismiss keyboard shortcuts dialog.
5. Press keys to perform keyboard shortcuts.
6. Notice shortcuts requiring note to be selected show error message.
7. Notice **_Open Search_** and **_New Note_** keyboard shortcuts work without selecting note in list.
8. Select note in list.
9. Press keys to perform keyboard shortcuts.
10. Notice keyboard shortcuts work as expected.

#### Small Device in Landscape and Portrait or Large Device in Portrait
1. Launch app without selecting note in list.
2. Press `CTRL` `,` keys.
3. Notice keyboard shortcuts dialog is shown.
4. Dismiss keyboard shortcuts dialog.
5. Press keys to perform keyboard shortcuts.
6. Notice shortcuts requiring note to be selected show error message.
7. Notice **_Open Search_** and **_New Note_** keyboard shortcuts work without selecting note in list.
8. Select note in list with markdown enabled.
9. Select _**Edit**_ tab.
10. Press `CTRL` `,` keys.
11. Notice keyboard shortcuts dialog is shown.
12. Dismiss keyboard shortcuts dialog.
13. Press keys to perform keyboard shortcuts.
14. Notice shortcuts work as expected.
15. Select _**Preview**_ tab.
16. Press `CTRL` `,` keys.
17. Notice keyboard shortcuts dialog is shown.
18. Dismiss keyboard shortcuts dialog.
19. Press keys to perform keyboard shortcuts.
20. Notice shortcuts work as expected.
21. Notice shortcuts requiring _**Edit**_ to be selected show error message.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

### CODE REVIEW

**Review by SylvesterWilmott — APPROVED** [review]
Looks good and works as intended, Thanks @theck13

**Comment by nbradbury** [comment]
@theck13 I just assigned myself this PR, but then I read that it requires a hardware keyboard, which I don't have. I'll unassign myself and ask my teammates if any of them have a hardware keyboard.

**Review by AmandaRiu — COMMENTED** [review]
@theck13 I was able to test landscape mode with a tablet, but unfortunately the attached keyboard will not work in portrait mode for some odd reason. I'm using a Pixel C. Here are some things I noted during testing:
- The `ctrl+g` and `ctrl+shift+g` while search results are displayed don't do anything for me and don't show any kind of error message. Is this option only available in portrait mode for large devices?
- I'm not sure if this is related to this PR or not but I thought I'd mention it anyway. When I toggle preview it un-toggles itself a second later. Is that expected? Doesn't matter if I do it with or without the keyboard shortcut - the result is the same. 

@ThomazFB  I notice you have this assigned to yourself as well. Are you able to test the portrait mode steps?

**Comment by theck13** [comment]
> The `ctrl+g` and `ctrl+shift+g` while search results are displayed don't do anything for me and don't show any kind of error message. Is this option only available in portrait mode for large devices?

Yeah, those options are only available after tapping a note in the search results and viewing the matches with a search match bar in the editor, which is only shown in portrait orientation or a small device in landscape orientation.  Messages should be shown when those keyboard shortcuts are used in portrait orientation or on a small device in landscape orientation.  Let me know if they aren't.

> I'm not sure if this is related to this PR or not but I thought I'd mention it anyway. When I toggle preview it un-toggles itself a second later. Is that expected? Doesn't matter if I do it with or without the keyboard shortcut - the result is the same.

Yeah, that's a known issue.  It's unrelated to these changes and it's due to some unknown change to Google App Engine.  Unfortunately, we won't be able to fix it until Simperium is rewritten.

**Comment by theck13** [comment]
> The `ctrl+g` and `ctrl+shift+g` while search results are displayed don't do anything for me and don't show any kind of error message. Is this option only available in portrait mode for large devices?

@AmandaRiu, after thinking about this some more, I think we should remove the **_Next Match_** and **_Previous Match_** shortcuts as well as the **_Search_** section from the dialog or just go to the next/previous match in the editor even if the search match bar isn't shown in that layout on large devices in landscape orientation.  I think keeping the shortcuts would be better for those devices since they are more likely to have hardware keyboards.  I added those shortcuts in b305b380.

**Comment by AmandaRiu** [comment]
>  Messages should be shown when those keyboard shortcuts are used in portrait orientation or on a small device in landscape orientation. Let me know if they aren't.

I'm unable to test that since I can't get my keyboard to work when in portrait mode 😢 

> > The `ctrl+g` and `ctrl+shift+g` while search results are displayed don't do anything for me and don't show any kind of error message. Is this option only available in portrait mode for large devices?
> 
> @AmandaRiu, after thinking about this some more, I think we should remove the **_Next Match_** and **_Previous Match_** shortcuts as well as the **_Search_** section from the dialog or just go to the next/previous match in the editor even if the search match bar isn't shown in that layout on large devices in landscape orientation. I think keeping the shortcuts would be better for those devices since they are more likely to have hardware keyboards. I added those shortcuts in [b305b38](https://github.com/Automattic/simplenote-android/commit/b305b3806d54020f73f5d424f085c7fe28532443).

@theck13 The shortcuts in landscape mode on my Samsung Tab S4 work! Much more expected experience, though there is no visual indication that anything is happening. For example, in this clip below I'm in a note that has multiple results for the search term "new", but you'll see that I there isn't any visual feedback that I'm scrolling through the various instances of "new" while moving around using the shortcut keys. I only know that I hit the beginning or end when I see the toast message:


https://user-images.githubusercontent.com/5810477/106634599-ec85a200-654d-11eb-97b1-8cf3618ea266.mp4

**Comment by theck13** [comment]
> Much more expected experience, though there is no visual indication that anything is happening... I only know that I hit the beginning or end when I see the toast message

Yeah, that's not ideal.  A good enhancement would be to add something to show which match you're on.  I'll check the other platforms and talk to @SylvesterWilmott about how we can handle that.  If we decide to add something, we'll do it outside of this pull request so that the keyboard shortcut changes are separate.

**Comment by AmandaRiu** [comment]
Looks like this PR got lost in the team shuffle last year and was stalled. Work on simplenote is not actively happening at this point but for now I've been instructed to unassign myself from it and when work resumes we can pick this one up and see about getting it merged. See p1647978271817809-slack-C036Y8QL4

**Pull request closed without merging**
