### PR TITLE
Add Style Setting (Part 2)

### PR DESCRIPTION
**Pull request by theck13**
### Fix
This is the second part in a series of pull requests to add a style setting to the app.  The pull requests are split into parts in an attempt to make the changes smaller.  This part adds the ***Black*** style.  See the screenshots below for illustration.

add_style_setting_all_02

#### Note
Contact me for an installable build.

### Test
1. Open navigation drawer.
2. Tap ***Settings*** item in drawer.
3. Tap ***Style*** item under ***Appearance*** section.
4. Notice ***Style*** screen with ***Default***, ***Black***, and ***Classic*** styles.
5. Tap ***Black*** style.
6. Notice ***Black*** style is selected and app has ***Black*** styling.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.  `RELEASE-NOTES.txt` will be updated once the styles feature is complete.

### CODE REVIEW

**Review by anitaa1990 — APPROVED** [review]
Really cool to see the color changes in the app 😍 Tested in dark and light mode and everything works great 👍 Will wait for design review before merging!

**Comment by theck13** [comment]
After chatting with @SylvesterWilmott, I added the `sheetBackgroundColor` attribute in eb593c0 so that bottom sheets can have a different background color than `mainBackgroundColor`.

**Review by SylvesterWilmott — APPROVED** [review]
Thanks @theck13 everything looks good!

**Comment by theck13** [comment]
Thanks, @SylvesterWilmott!  @anitaa1990, let me know if you have any questions about `sheetBackgroundColor` in eb593c0.  Otherwise, these changes are good to merge whenever you're ready.

**Review by anitaa1990 — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
