### PR TITLE
Update App Store description

### PR DESCRIPTION
**Pull request by loremattei**
This PR updates the app description for the app store. 

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks good!

In the Play Store we also have the short description (before the description is expanded). Is that something we have to set?

**Comment by theck13** [comment]
Yes, the short description is a separate field with a maximum of 80 characters.

**Comment by SylvesterWilmott** [comment]
@loremattei can we set the Android short description as well?

`Simplenote is an easy way to take notes, create to-do lists and capture ideas.`

**Comment by loremattei** [comment]
@SylvesterWilmott yes, we can. But I see that the new one is 80 chars... usually this will result in translations that are too long. IIRC Google guideline is to keep the English version around 50%... in my experience this is too restrictive, but 80% is usually recommendable. 
I just wanted to give you the heads up... if you want to try to send this one and check what comes back from translation, I'm fine with this. Just let me know :-)

**Comment by SylvesterWilmott** [comment]
@loremattei

Short description: `Take notes, create to-do lists, capture ideas, and more.`

**Comment by loremattei** [comment]
Thanks @SylvesterWilmott! I just pushed an update to the strings.

**Pull request merged**
