### PR TITLE
Issue/update sheet buttons

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the buttons in the history and info bottom sheets.

#### History
The buttons in the history bottom sheet, _**Cancel**_ and _**Restore**_, had a `selectableItemBackgroundBorderless` background, which doesn't follow the guidelines for [text buttons in Material documentation](https://material.io/design/components/buttons.html#text-button).  The background was updated to `selectableItemBackground`, which mimics the guidelines as shown [here](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F14c0HqGVluF8KDMuij_AV5puYPmorTU2u%2Ftext-buttons-states.png).  See the screenshots below for illustration.

simplenote_history_buttons

#### Info
The share button in the info bottom sheet was missing an icon and the view width was set to `match_parent`, which made the tapped background fill the bottom sheet.  Also, the view's content description was set to `@string/copy`, which incorrectly read as "Copy" for the share button.  The view's width, content description, and icon were updated.  Also, a hint and haptic feedback were added to both the share and copy buttons when long-pressed.  See the screenshots below for illustration.

simplenote_info_compare

simplenote_info_all

### Test
1. Tap unpublished note in list.
2. Tap **_History_** action in toolbar.
3. Long-press **_Cancel_** button in bottom sheet.
4. Notice button background as shown above.
5. Long-press **_Restore_** button in bottom sheet.
6. Notice button background as shown above.
7. Tap **_Info_** action in toolbar.
8. Notice **_Share_** button icon as shown above.
9. Long-press **_Share_** button in bottom sheet.
10. Notice button background as shown above.
11. Notice **_Share_** hint and haptic feedback.
12. Tap **_Share_** button in bottom sheet.
13. Tap **_Publish_** button in sharing sheet.
14. Wait for note to be published.
15. Tap **_Info_** action in toolbar.
16. Long-press **_Copy_** button in bottom sheet.
17. Notice button background as shown above.
18. Notice **_Copy_** hint and haptic feedback.

### CODE REVIEW

**Comment by roundhill** [comment]
Tested well! Thanks for the nice fixes @theck13. :shipit:

**Comment by roundhill** [comment]
Updates seem ok @theck13. I'm curious about the dark icon color:

screen shot 2019-01-17 at 5 01 43 pm

I think it should be the brighter blue color, like when you toggle markdown?

screen shot 2019-01-17 at 5 03 12 pm

**Comment by theck13** [comment]
I used the existing `iconTintColor` attribute for tinting the icons, which uses the [`simplenote_light_grey`](https://github.com/Automattic/simplenote-android/blob/2a8d2074f925d36c311d12cd32d35f220d6ac9fc/Simplenote/src/main/res/values/colors.xml#L16)(`#777777`) or [`simplenote_dark_text`](https://github.com/Automattic/simplenote-android/blob/2a8d2074f925d36c311d12cd32d35f220d6ac9fc/Simplenote/src/main/res/values/colors.xml#L23)(`#71889f`) color when the app is using the `Light` or `Dark` theme.  Do you think we should use a different color attribute or change the `iconTintColor` value for `Dark`?

**Comment by roundhill** [comment]
> or change the `iconTintColor` value for `Dark`

I think we should do this. It's hard to find a place where we have icons like that, but the tags settings activity makes them blue: 

screen shot 2019-01-18 at 9 30 48 am

**Comment by theck13** [comment]
I updated the attribute to `simplenote_blue`(`#4895d9`) in 41843a1.  See the screenshots below for illustration.

simplenote_info_color

**Pull request merged**
