### PR TITLE
[Bug] If a deeplink is malformed or missing data we show auth screen.

### PR DESCRIPTION
**Pull request by notandyvee**
### Fix

There is an edge case with magic link deeplinking. If the url is malformed or the client cannot properly find the email/code as an example, the app doesn't ever show up. You do see a toast, but this is weird behavior. This PR updates that so that we show the auth activity in this case.

| Before    | After |
| -------- | ------- |
| before-magic-link-no-work  | after-magic-link-no-working    |

Additionally, while I was here I realize the magic link on this screen was missing a loading indicator. It's not clear this is happening. On slower networks this could be an issue. A loading dialog will do for now.

### Test

What I did to test is to put this link in google keep: `https://app.simplenote.com/login?email=&auth_code=0V6GUL`. You can open the link and it will trigger the deeplink. Do not paste it on chrome. Doing that ignores any deeplink.

- [ ] Trigger the malformed deeplink, like clicking the link.
- [ ] You should see a toast that something went wrong and you should be taken to the authentication screen.

### Release

N/A

### CODE REVIEW

**Comment by mokagio** [comment]
@notandyvee @danilo04 I'm working on more release automation and aim to have a quick 2.34 release to test it, see p1725313949594039-slack-C036Y8QL4

It would be great to get this reviewed so we can make it part of it?

I'll make sure to track here when the release starts, so that we can adjust the base branch accordingly:

- `trunk` if reviewed and merged before the code freeze
- `release/2.34` otherwise

Thanks!

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/simplenote-android/milestone/45">2.34 ❄️</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by mokagio** [comment]
@notandyvee @danilo04 FYI, I merged `trunk` in here because of a change in the GitHub check requirement which would otherwise have prevented this PR to land in either `trunk` or `release/2.34`.

Also, given the release 2.34 code freeze has started, I updated the target branch for this PR to it.

**Review by danilo04 — APPROVED** [review]
This is working as expected @notandyvee. Good job :shipit:

**Pull request merged**
