### PR TITLE
Note Shortcut Widget

### PR DESCRIPTION
**Pull request by robertoissc**
Implementation of note shortcut widget #232 

This widget allows the user to select an existing note and add a shortcut to the homescreen, it updates periodically to detect changes on the notes title or status.

Please share feedback on design and functionality.

screenshot_20190126-174924
screenshot_20190126-174931
screenshot_20190126-174955

### CODE REVIEW

**Comment by roundhill** [comment]
Pretty cool @robertoissc! 

@drw158 wondering if you have any design thoughts here?

**Comment by drw158** [comment]
I'm not too familiar with other apps that might do this but here is some feedback:

- No simplenote icon needed
- Remove italic
- Use black or dark gray instead of blue
- Consider using a lighter weight font as used in the Simplenote app

**Comment by robertoissc** [comment]
Thanks! I'll work on this changes and get back to you 👌

**Comment by drw158** [comment]
Rounded corners to follow the guidelines would be great! It feels a bit incomplete right now and the corners will help.

This is a good first step, but I'd also like to see more of the note if possible. Maybe, as the widget grows, it can show the content of the note as well as the title.

**Comment by robertoissc** [comment]
Thanks @drw158, I'll make this change.

And I totally agree with you, this can be a start. Maybe in the next iteration if you make the widget bigger it can show you a content preview.

Also I'm thinking about a `NoteListWidget` as discussed in #232 that shows a list of the notes with title and content preview. 💯

**Comment by robertoissc** [comment]
Latest update:
screenshot_20190130-165538

**Comment by roundhill** [comment]
Just test this out a bit. Here's a few UX bugs:

* If you change the title of a note that is a widget, it isn't reflected in the widget (may not be possible to fix?)
* If you sign out of the app, and then tap on a widget, you get a blank note editor. Same issue if you delete the note, then empty the trash.

Also, can an ellipsis be added to note titles that are too long and get cut off?

screen shot 2019-01-30 at 5 01 16 pm

**Comment by robertoissc** [comment]
Hey @roundhill, thanks for the feedback.

Currently the widget updates every 6 hours to detect changes in the notes.
- It updates the title of the notes.
- If it does not found the note it disables the click functionality for that widget and adds the legend "Note Not Found" so the user can remove the widget since it's not possible to do it automatically.

Actions:
- Reduce the update interval. The minimum time interval for this is 1/2 hour.
- Trigger a manual widget update on sign out, emptying trash and note update.
- I'll add an ellipsis to note titles that are too long. 😉 

Please let me know your thoughts! 😃

**Comment by robertoissc** [comment]
Maybe on the configure activity? 🤔
On top of the note list?
"The widget will update periodically" 

Should I drop the manual update? 🤔

Thanks!

**Comment by roundhill** [comment]
> On top of the note list?
> "The widget will update periodically"

I like it 👍

**Comment by robertoissc** [comment]
Hey @roundhill, I've added some updates based on your feedback

- Add ellipsis to note titles that are too long
- Request update of widgets when notes change
- Request update of widgets when user signs out
- Request update of widgets when user logs in
- Enforce user log in when adding a new widget
- Minor fixes and refactor

**Comment by SergioGeeK7** [comment]
Hey guys, have you had time to review this pull request? many users are requesting this feature

**Pull request merged**
