### PR TITLE
Update Edit Tags

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the list item layout on the ***Edit tags*** screen.  These changes include:
- Add minimum height of row to 48dp
- Add trash button hint message on long-press
- Remove horizontal dividers between list items
- Remove vertical dividers between count text and trash button

See the screenshots below for illustration.

update_edit_tags

### Test
1. Open navigation drawer.
2. Tap ***Edit*** button in ***Tags*** group.
3. Notice updated list item layout.
4. Long-press trash button.
5. Notice ***Delete tag*** message.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks good! Were you able to fix the issue with the mysterious row heights?

**Comment by theck13** [comment]
I assigned the minimum height of the row view to be 48dp [here](https://github.com/Automattic/simplenote-android/pull/816/files?file-filters%5B%5D=.xml#diff-747389b6169d1305e015551cb85dd6cbR11).  Also, I assigned the minimum height and width of the _*Delete*_ button to 48dp.  That button uses a [24dp square icon with a 12dp padding on all sides](https://github.com/Automattic/simplenote-android/pull/816/files?file-filters%5B%5D=.xml#diff-747389b6169d1305e015551cb85dd6cbR55-R58), which makes it 48dp as well.  Due to that, the row should have at least 48dp height.

**Comment by AmandaRiu** [comment]
@theck13 @SylvesterWilmott is this good to merge?

**Comment by theck13** [comment]
@SylvesterWilmott mentioned he wanted to review it at least once more.

**Comment by SylvesterWilmott** [comment]
Tested on device and height of rows on device confirmed to be 46dp. Maybe we could just make the minimum height 50dp to account for the missing 2dp?

**Comment by theck13** [comment]
I would trust the code here more than the layout on a specific device or Android version.  If we tested the height in all devices with all Android versions and it was 46dp, then we might want to adjust the value a little.  Making an adjustment for this one value goes against all the assumptions we make with other values for similar attributes.

**Comment by theck13** [comment]
I removed the tag icon from the list in 1992b8a5 as we discussed, @SylvesterWilmott.  See the screenshots below for illustration.

update_edit_tags_again

**Comment by SylvesterWilmott** [comment]
Looks good @theck13 !

**Pull request merged**
