### PR TITLE
Material Design for settings screen on pre-Lollipop devices

### LINKED ISSUE #391: Material Design on pre-Lollipop devices
There are few user interface elements such as switches which aren't in Material Design style when running application on pre-Lollipop devices.

- [x] Switches in note info bottom sheet
- [x] Tag renaming dialog
- [x] Tags input field
- [x] Switches in settings
- [x] Dialogs in settings
- [x] Settings section headers 

# Question

I can try and create pull request(s) solving these issues but I have a question whether I should make these changes in one pull request or few separate focused on specific UI elements?

# Images

Switches
Rename dialog
Settings headers
Settings dialogs

### PR DESCRIPTION
**Pull request by Tunous**
The implementation of Material Design for pre-Lollipop devices in this change was done by switching to support version of fragments and including [fix library](https://github.com/Gericop/Android-Support-Preference-V7-Fix). I decided to go with this library and few manual modifications as there were a handful of bugs related to padding, colors, etc which would introduce a lot of boilerplate to the codebase.

I also made the following separate pull request: https://github.com/wordpress-mobile/PasscodeLock-Android/pull/40 and commented-out related code to be able to test changes. If that change is included and I didn't fail it should be possible to re-enable the code and update the library to have everything working correctly again.

Closes #391

### CODE REVIEW

**Comment by roundhill** [comment]
So wordpress-mobile/PasscodeLock-Android#40 is required for this to still support the passcode lock?

**Comment by Tunous** [comment]
Yes. Support fragments aren't compatible with regular.

**Comment by roundhill** [comment]
@Tunous `develop` now uses the latest passcode lock lib, so feel free to update this to have the passcode lock activated.

**Comment by Tunous** [comment]
Done.

**Comment by roundhill** [comment]
@Tunous I merged the cleanup PR and now there's conflicts, would you mind cleaning them up?

**Comment by Tunous** [comment]
Sure, I'll get that fixed now.

**Comment by Tunous** [comment]
Done.

**Comment by roundhill** [comment]
Excellent @Tunous, thanks again for contributing. This will be really nice for 4.X users.

**Pull request merged**
