### PR TITLE
Update Status Bar

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the status bar color and style for all screens.  A side effect of the recent status bar changes in https://github.com/Automattic/simplenote-android/pull/644 is that the color is different on various screens.  It's not very obvious using the ***Light*** theme, but it's more prominent using the ***Dark*** theme.  See the screenshots and tables below for illustration and color values.  ***Past*** is state before the recent changes.  ***Present*** is state after the recent changes.  ***Future*** is state after these changes.

status_light

Past|Present|Future
-|-|-
`#757575`|`#757575`|`#4895d9`
`#1b74af`|`#1b74af`|`#2291db`
`#bbbbbb`|`#dddddd`|`#cccccc`
`#cccccc`|`#c3c3c3`|`#cccccc`
`#cccccc`|`#cccccc`|`#cccccc`
`#cccccc`|`#cccccc`|`#cccccc`
`#cccccc`|`#cccccc`|`#cccccc`

status_dark

Past|Present|Future
-|-|-
`#757575`|`#757575`|`#4895d9`
`#1b74af`|`#1b74af`|`#2291db`
`#212326`|`#747678`|`#1b1d1f`
`#000000`|`#5e5e5e`|`#1b1d1f`
`#000000`|`#000000`|`#1b1d1f`
`#000000`|`#000000`|`#1b1d1f`
`#000000`|`#000000`|`#1b1d1f`

### Test
Launching the app and visiting multiple screens as well as switching between ***Dark*** and ***Light*** modes is the best way to test those changes.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Comment by theck13** [comment]
That's because I forgot to include the `values-night-v21/styles.xml` file.  Ha!  I added the file in 147129d.

The slightly darker status bar is to allow the navigation drawer to be shown behind the status bar when sliding in and out.  That's true for both _**Light**_ and _**Dark**_ themes.  It also allows the the navigation drawer list to be shown behind the status bar while scrolling up and down when you have many tags in the list.  See the animation below for illustration.

status_bar

**Comment by theck13** [comment]
@AmandaRiu, I resolved the merge conflicts and removed the `[status] needs design review` label.  These changes are good to merge whenever you're ready.

**Comment by bummytime** [comment]
This is really great stuff @theck13 — thank you!

**Comment by AmandaRiu** [comment]
:shipit:

**Pull request merged**
