### PR TITLE
Update Android X

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the Android support library from `com.android.support` to `androidx` to close https://github.com/Automattic/simplenote-android/issues/719.  This is a prerequisite for the login/signup changes to follow.  The build error shown below is due to the Sentry plugin and will be addressed separately.

```
WARNING: API 'variantOutput.getProcessManifest()' is obsolete and has been replaced with 'variantOutput.getProcessManifestProvider()'.
It will be removed at the end of 2019.
```

### Test
Even though these changes affect many files and screens throughout the app, only smoke testing is required since the build system takes care of validating most of the changes.  Verifying the app doesn't crash while logging in, creating notes, viewing info, enabling/disabling markdown, applying history, changing settings, etc. should be enough.

### Review
Only one developer is required to review these changes, but anyone can perform the review.  Additionally, I requested @loremattei as a reviewer since I saw he added the `gradle.properties` file to `.gitignore` in https://github.com/Automattic/simplenote-android/commit/a0d5fb7b0a41315ed92bf1a1a5378de599081b0d.  The project-level `gradle.properties` file is required for the Android X library.  @loremattei, is there a reason we shouldn't add that file to the repository for release purposes?

### CODE REVIEW

**Comment by loremattei** [comment]
Hey @theck13! I have some entries that shouldn't be added to the git repository in my current `gradle.properties`. 
I'll double check if we can move them.

**Comment by theck13** [comment]
Thanks, @loremattei!  I moved those values from `gradle.properties` to `Simplenote/gradle.properties` and added `gradle.properties` back to `.gitignore`.

**Comment by theck13** [comment]
@loremattei, did you find a way to move the entires in your current `gradle.properties` file so they won't be pushed to the repository?

I tried moving the following entries from `gradle.properties` to `Simplenote/gradle.properties`, but that is causing build errors since the `Simplenote/gradle.properties-example` file is being copied to `Simplenote/gradle.properties` *after* the dependencies are resolved.  If we leave these entries in the `gradle.properties`, the build succeeds.
```
android.enableJetifier = true
android.useAndroidX = true
```

**Comment by theck13** [comment]
@roundhill, I requested you as an additional reviewer since we updated the Wear module and you have experience with that.  Personally, I don't have a Wear device.  Can you test these changes for Wear?

**Comment by theck13** [comment]
@jtreanor / @jkmassel / @loremattei, I updated the secrets repository by removing the `gradle.properties` file and moving the entries to the `SImplenote/gradle.properties` file.  That way we can unignore the `gradle.properties` file and the Android X entries can be used there to fix the build.  Let me know if this causes any issues with the release process.

**Comment by bummytime** [comment]
Pinging @nbradbury @AmandaRiu and @anitaa1990. If anybody could take a peek at this PR it would be _greatly_ appreciated. 🙇

**Comment by bummytime** [comment]
(Also @maxme in case you have some bandwidth 😄)

**Comment by anitaa1990** [comment]
Sorry, I completely missed this last week! Taking a look now

**Comment by loremattei** [comment]
> @jtreanor / @jkmassel / @loremattei, I updated the secrets repository by removing the `gradle.properties` file and moving the entries to the `SImplenote/gradle.properties` file. That way we can unignore the `gradle.properties` file and the Android X entries can be used there to fix the build. Let me know if this causes any issues with the release process.

Hey @theck13, I think it doesn't cause any critical issues. Thanks for checking! 
I'd like to run a quick test to check if any changes to the release tools are required, but I can't find the commit hash you pinned in `.configure` in the mobile-secrets repository. 
Did you push it?

**Comment by maxme** [comment]
Changes related to `useAndroidX` and `enableJetifier` set in the root `gradle.properties` look good to me.

(For reference, there is also a way to force the parameter from command line: `./gradlew assembleDebug -Pandroid.useAndroidX=true -Pandroid.enableJetifier=true`).

**Comment by theck13** [comment]
> I can't find the commit hash you pinned in `.configure` in the mobile-secrets repository.
> Did you push it?

I thought I did, but I guess I didn't.  I just pushed again.  Can you try the release check again, @loremattei?

**Comment by loremattei** [comment]
@theck13 I gave it a spin and I verified that the release tools work without needing any changes. 👍

**Comment by theck13** [comment]
Since these changes have been approved by multiple developers and passed the release process, I'll merge it.

**Pull request merged**
